apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: "keycloak-identity"
spec:
  type: 0
  resourceID: /subscriptions/52512f28-c6ed-403e-9569-82a9fb9fec91/resourceGroups/aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-pod-ident
  clientID: 236020b7-4b77-44c8-abfe-5852e6a7b572

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: "keycloak-identity-binding"
spec:
  azureIdentity: "keycloak-identity"
  selector: "keycloak-identity-binding"
