apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: keycloak-secrets

spec:
  provider: azure
  secretObjects:
    - data:
        - key: dbpassword
          objectName: dbpassword
      type: Opaque
      secretName: sql-server-database-creds

  parameters:
    keyvaultName: benc
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
    usePodIdentity: "true"
    objects: |
      array:
        - |
          objectName: dbpassword
          objectType: secret
          objectVersion: ""
