#
# This is an example values file, it provided as a reference
# It is not intended to be used as-is and there is no assurance the image ghcr.io/benc-uk/keycloak will remain available.
#

replicaCount: 2

image:
  registry: ghcr.io
  repository: benc-uk/keycloak
  tag: latest

keycloak:
  httpPort: 7000
  clustered: true
  proxyMode: edge
  adminUser: superAdmin
  healthCheckPath: /auth/realms/master
  hostnamePath: auth

  database:
    passwordSecret:
      name: sql-server-database-creds
      key: dbpassword
    username: "dbadmin"
    host: "benc.database.windows.net"
    databaseName: "keycloak"

ingress:
  className: nginx
  enabled: true
  host: keycloak.kube.benco.io
  tls:
    enabled: true
    secretName: benco-io-cert

# Everything below here is just to get the dbpassword secret from Key Vault using pod identity

podLabels:
  aadpodidbinding: keycloak-identity-binding

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "keycloak-secrets"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/secrets-store
    readOnly: true
