{{- if not .Values.keycloak.adminPasswordSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-admin-secret
  labels:
    {{- include "keycloak-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ randAlphaNum 20 | quote }}
{{- end }}